# Nazwa aplikacji
spring.application.name=ksiegarnia-online


# ==========================
# BAZA H2
# ==========================


# Tworzymy bazę w pamięci RAM
spring.datasource.url=jdbc:h2:mem:ksiegarnia


# Sterownik bazy
spring.datasource.driver-class-name=org.h2.Driver


# Login bazy
spring.datasource.username=sa


# Hasło puste
spring.datasource.password=



# ==========================
# JPA / HIBERNATE
# ==========================


# Automatyczne tworzenie tabel
spring.jpa.hibernate.ddl-auto=create


# Pokazuje SQL w konsoli
spring.jpa.show-sql=true



# ==========================
# PANEL H2
# ==========================

spring.h2.console.enabled=true


# Adres:
# http://localhost:8080/h2-console



# ==========================
# THYMELEAF
# ==========================

spring.thymeleaf.cache=false



# ==========================
# SWAGGER
# ==========================

springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.path=/swagger-ui.html
